# vim: foldmethod=marker foldlevel=0

if [[ -f $HOME/.profile ]]; then
  source $HOME/.profile
fi

# Section: oh-my-zsh config {{{1

export ZSH=$HOME/.oh-my-zsh

DISABLE_AUTO_UPDATE="true"
plugins=(git rails)

export PATH=$PATH:/usr/local/bin/:$HOME/bin

source $ZSH/oh-my-zsh.sh

# }}}1
# Section: Autocomplete {{{1

source $HOME/.dotfiles/zsh/theme.zsh-theme

if which kubectl &> /dev/null; then
  source <(kubectl completion zsh)
fi

if which helm &> /dev/null; then
  source <(helm completion zsh)
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="$HOME/.nvm"

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# }}}1
# Section: Git {{{1

if which nvim &> /dev/null; then
  export GIT_EDITOR=nvim
else
  export GIT_EDITOR=vim
fi

# }}}1
# Section: Auto Config {{{1

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt beep nomatch notify autocd
unsetopt appendhistory extendedglob share_history
bindkey -v

zstyle :compinstall filename "$HOME/.zshrc"

autoload -Uz compinit
compinit

# }}}1
# Section: Env {{{1

export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:\
$HOME/.dotfiles/bin:\
$HOME/.rvm/bin:\
$HOME/.config/composer/vendor/bin:\
$HOME/bin:\
$ANDROID_HOME/tools:\
$ANDROID_HOME/platform-tools:\
$HOME/Library/Python/3.6/bin:\
$HOME/.tst/bin

if [[ `uname` = 'Darwin' ]]; then
  export TERM=xterm-256color-italic
else
  export TERM=xterm-256color
fi

export GOPATH=$HOME/.gocode

if which yarn &> /dev/null; then
  export PATH=$PATH:`yarn global bin`
fi

export PKG_CONFIG_PATH=$(pkg-config --variable pc_path pkg-config):/usr/local/lib/pkgconfig/

export FZF_DEFAULT_OPTS='-i'

export SHELL=`which zsh`

# }}}1
# Section: Aliases {{{1

if [[ `uname` = 'Linux' ]]; then
  alias ls='ls --color=auto --group-directories-first'
fi

alias grep='grep --colour=auto'
alias la='ls -A'
alias ll='ls -Ahl'
alias py='python'
alias pyc="rm *.pyc"

# }}}1
# Section: Config {{{1

bindkey '^R' history-incremental-search-backward

# }}}1
