# environment variables and source files
export PATH=$PATH:$HOME/.dotfiles/bin:$HOME/.android-studio/bin

export PKG_CONFIG_PATH=$(pkg-config --variable pc_path pkg-config):/usr/local/lib/pkgconfig/
export GIT_EDITOR=vim

# oh-my-zsh rc file and theme file
source $HOME/.dotfiles/zsh/zshrc.aux
source $HOME/.dotfiles/zsh/theme.zsh-theme

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt beep nomatch notify autocd
unsetopt appendhistory extendedglob share_history
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/lucas/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Custom alias
#alias open='gnome-open'
if [[ `uname` = Linux ]]; then
	alias grep='grep --colour=auto'
	alias la='ls -A --group-directories-first'
	alias ll='ls -Al --group-directories-first'
	alias ls='ls --color=auto --group-directories-first'
fi
alias py='python'
alias pyc="rm *.pyc"
alias clear='echo "ctrl+l"'
alias cs50="cd ~/Dropbox/CS50/"

function xre() {
	xrdb ~/.Xresources
}

function gpp() {
	g++ -ggdb -std=c++11 -Wall -Werror ${1}.cpp -lcrypt -lm -o $1;
}

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
